### ISSUE TITLE
`serve` doesn't support entrypoints

### ISSUE THREAD

**Issue by charliermarsh** [AnswerDotAI/fasthtml#106]
Congrats on the release!

It looks like the current [serve](https://github.com/AnswerDotAI/fasthtml/blob/6e8e8adf9839474b2ee3807d1e1876c1414049b3/fasthtml/fastapp.py#L65) implementation does some `if __name__ == '__main__'` detection, which makes it a no-op when exposed via an entrypoint script or other mode of execution.

Here's an example with Poetry. Create a directory `foo` with the following `pyproject.toml`:

```toml
[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python-fasthtml = "^0.2.1"

[tool.poetry.scripts]
app = "foo.app:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Then create `src/foo/app.py` with:

```python
from fasthtml.common import *

app,rt = fast_app()

@rt('/')
def get(): return Div(P('Hello World!'), hx_get="/change")

def main():
    print("Serving...")
    serve()

if __name__ == '__main__':
    main()
```

Running `poetry run python ./src/bar/app.py` yields:

```
Serving...
Link: http://localhost:5001
INFO:     Will watch for changes in these directories: ['/Users/crmarsh/workspace/bar']
INFO:     Uvicorn running on http://0.0.0.0:5001 (Press CTRL+C to quit)
INFO:     Started reloader process [75724] using WatchFiles
INFO:     Started server process [75726]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

Meanwhile, `poetry run app` prints and exits immediately:

```
Serving...
```
